version: "3"

services:
  jupyter:
    restart: always
    build: ./
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/jupyter
    command: jupyter notebook --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
